version: "3.4"
volumes:
  shared-volume:
services:
  prom:
    image: prom/prometheus:${PROMETHEUS_VERSION}
    container_name: prom
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ${GITHUB_WORKSPACE}/.github/prometheus:/etc/prometheus
    ports:
      - "9090:9090"
  redis:
    image: redis:6-alpine
    container_name: redis
    command: redis-server
    ports:
      - 6379:6379
  swoole:
    container_name: "swoole"
    depends_on:
      - prom
      - redis
    environment:
      REDIS_SERVER_HOST: ${REDIS_SERVER_HOST}
    build:
      context: .
      dockerfile: swoole.dockerfile
      args:
        SWOOLE_DOCKER_VERSION: ${SWOOLE_DOCKER_VERSION}
    volumes:
      - "${GITHUB_WORKSPACE}:/imi:rw"
    working_dir: /imi
    command: tail -f /dev/null
    ports:
      - "8080:8080"
