name: Coding Standards

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-20.04
    env:
      SWOOLE_DOCKER_VERSION: 4.8-php8.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        run: |
          docker-compose -f ./.github/docker-compose.yml up -d swoole
          docker exec swoole php -v
          docker exec swoole composer -V
          docker exec swoole composer update --no-interaction --prefer-dist --no-progress

      - name: Coding Standards Tests
        run: docker exec swoole ./vendor/bin/php-cs-fixer fix --dry-run --diff
